[package]
name = "dof_calc"
version = "0.1.0"
authors = ["hekrause <hekrause@htwg-konstanz.de>"]

[dependencies]
measurements = { git = "https://github.com/hekrause/rust-measurements.git" }
serde = "1.0.18"
serde_derive = "1.0.18"
serde_json = "1.0.5"